name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Show Node.js version    
        run: npm --version
      
      - name: Create .env file
        run: echo "${{ secrets.DOT_ENV }}" > .env
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Truffle compile
        run: CI=true npx truffle compile
      
      - name: Run coverage
        run: npx truffle run coverage
      
      - name: Generate .coveralls.yml file
        run: echo "${{ secrets.DOT_COVERALLS_YML }}" > .coveralls.yml
      - name: Send Coverage information to Coveralls
        run: cat coverage/lcov.info | npx coveralls

      - name: Cleanup .env file
        run: rm -f .env
      - name: Cleanup .coveralls.yml file
        run: rm -f .coveralls.yml